### PR TITLE
[Fix]: explicitly sort files before selecting by index

### PR DESCRIPTION
**Pull request by EnergoStalin**
Sometimes without sorting it might not work for example selecting 6 episode of Yozakura-san family from Anilibria would result in ep 1 being loaded without sorting.

### CODE REVIEW

**Comment by sweetbbak** [comment]
I'll merge but I think I'm going to ultimately change this. I kinda don't like this method of selecting episodes, its hard to tell what is what. I think it would be far better to use the fzf library to select episodes by name. Luckily it takes a slice of any type. I think something like this would be nice:

this is just semi-pseudo code
```
        files := torrent.Files()
	idx, err := fzf.Find(
		files,
		func(i int) string {
			return files[i].Path()
		},
	)
```
and then request for that file to be played on the backend by adding a query parameter to the handler. Might as well just add by_filepath, by_filename etc...

It would pretty much just require reworking this function and working on all the places that make requests to the http server to the updated url query parameters.
```
// handler for ServeTorrent
func (c *Client) handler(w http.ResponseWriter, r *http.Request) {
	ts := c.TorrentClient.Torrents()
	queries := r.URL.Query()
	// get hash of torrent
	hash := queries.Get("hash")
	// get episode
	ep, err := strconv.Atoi(queries.Get("ep"))
	if err != nil {
		http.Error(w, http.StatusText(400), http.StatusBadRequest)
		return
	}

	// idk why but this is always mangled af
	hash = strings.TrimSpace(hash)
	hash = strings.ReplaceAll(hash, "\n", "")

	if hash == "" {
		log.Println("server handler: Hash query is empty")
		return
	}

	for _, ff := range ts {
		<-ff.GotInfo()
		ih := ff.InfoHash().String()

		if ih == hash {
			f, err := GetVideoFile(ff, ep)
			if err != nil {
				log.Println(err)
				return
			}

			w.Header().Set("Content-Type", "video/mp4")
			http.ServeContent(w, r, f.DisplayPath(), time.Unix(f.Torrent().Metainfo().CreationDate, 0), f.NewReader())
		}
	}
}
```

**Comment by sweetbbak** [comment]
for reference[https://github.com/sweetbbak/toru/compare/main...new-server](https://github.com/sweetbbak/toru/compare/main...new-server)

**Comment by sweetbbak** [comment]
image
now it looks something like this

**Comment by EnergoStalin** [comment]
Yeah that approach definitely better. I would like to save current UX behaviour just enhancing it with fzf name based picker tho.

**Pull request merged**
