### PR TITLE
[toru] feat: add episode support

### PR DESCRIPTION
**Pull request by 0azis**
#7 based on issue, added support for series selection

### CODE REVIEW

**Comment by 0azis** [comment]
By the way, I have deleted some unnecessary prints, therefore, toru began to look more tidy

**Comment by sweetbbak** [comment]
Thanks! I'm going to create a dev branch and pull this into it so I can test it and make sure everything is all good. Looks good as far as I can see. My one nitpick is that the large majority of people are going to be streaming torrents that contain a single video file so I would like to add a check on the number of video files, if there is only one, then it will just start playing it without any user input. I'll check this out today though and try to get it merged soon.

**Comment by 0azis** [comment]
You can test it now :)

**Comment by sweetbbak** [comment]
Thanks! looks good.

**Pull request merged**
